version: '3.4'

services:  
  sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pa55W0rd"
    ports:
      - "1553:1433" 
      
  bookstore.api:
    image: ${DOCKER_REGISTRY-}bookstoreapi
    build:
      context: .
      dockerfile: BookStore.API/Dockerfile
    environment:
      DefaultSqlHost: "sql"      
      ASPNETCORE_ENVIRONMENT: Development 
    ports:
      - "8080:80"
    depends_on:
      - sql